### PR TITLE
flags bug fixes

### PR DESCRIPTION
**Pull request by mayank33**

### CODE REVIEW

**Comment by ninsbl** [comment]
After applying #24 locally, I still get this error message if I do not tick a "check option":
g.list [-](...)
ERROR: Value <[-]> out of range for parameter <type>
        Legal range: raster,raster_3d,vector,label,region,group,all

Ticking the "Ignore cases" box the error message changes to:
g.list [-i](...)
ERROR: Value <[-i]> out of range for parameter <type>
        Legal range: raster,raster_3d,vector,label,region,group,all

GRASS commands have no brackets around the flags. A proper call of g.list would be:
g.list type=vector or g.list -i type=vector

**Comment by ninsbl** [comment]
These changes allowed me to start g.list and gave the expected result (though I am no programer):

```
diff --git a/src/MainUI.cpp b/src/MainUI.cpp
index b66f311..9e1eddb 100644
--- a/src/MainUI.cpp
+++ b/src/MainUI.cpp
@@ -226,7 +226,7 @@ void MainUI::runModule(){
         std::string command = gmodule;
           if(!flag_list.empty())
           {
-            command = command+ " "+"[-";
+            command = command;
           }
         for (std::vector<std::string>::iterator it=flag_list.begin(); it != flag_list.end(); ++it) /*creation of widgets*/
                  {   
@@ -239,6 +239,7 @@ void MainUI::runModule(){
                       // std::string value = cb->checkState();
                       if(cb->isChecked())
                       {
+                         command = command + " " + "-";
                         if(d == "help")
                         {
                           common_flags = common_flags + " --help";
@@ -274,7 +275,7 @@ void MainUI::runModule(){
                  }
           if(!flag_list.empty())
           {
-            command = command + "] ";
+            command = command + " ";
           }

         for (std::vector<std::string>::iterator it=list.begin(); it != list.end(); ++it) /*creation of widgets*/

```

**Comment by mayank33** [comment]
Thanks. The PR is updated

**Comment by epifanio** [comment]
@mayank33 , I'm merging this to help the test. Did you had a look at the new branch were this and other issues (module ui size, and multiple module) are alredy fixed ?

**Pull request merged**
