### PR TITLE
All levels modules working, module dialog boxes coming

### PR DESCRIPTION
**Pull request by mayank33**

### CODE REVIEW

**Comment by rashadkm** [comment]
is this PR ready or in draft?. because it deletes the resources from source tree!

**Comment by mayank33** [comment]
I deleted them because my resources are different from yours so to avoid commiting them again and again and making it difficult for you to merge.

**Comment by rashadkm** [comment]
if your resource is working well. we should all use that instead of upstream

**Comment by mayank33** [comment]
I think you have checked that and it was not working for you. but we can check it once again

**Comment by rashadkm** [comment]
the current resource is working okay for me. but if you have a better one with updates. we can use that. if you make sure your resources are working in chrome and FF on atleast on another machine (which hasn't run webgrass yet). we can merge it. no problem.

even if there is conflict this can be done.

**Comment by rashadkm** [comment]
did you rebase with upstream?

git fetch upstream
git merge upstream/master ?

**Comment by mayank33** [comment]
Yes at the start of the week. Also made the changes by myself which you did to toolbar.

**Pull request merged**
